instance:
  name: webrise

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webrise
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml